### ISSUE TITLE
Readme examples don't work

### ISSUE THREAD

**Issue by dcohen21** [Spinoco/fs2-mail#18]
I'm looking into using fs2-mail for a new feature at my organization. I'm trying to familiarize myself with the API, but the examples in the Readme don't seem to work. Has the API changed considerably since the Readme was updated?

Specifically looking at the `Receiving emails` section, I'm having trouble with:
 - `clientTLS` (I created a new `SSLEngine` to bypass this issue)
 - `imap.client` - `client` doesn't look to be a part of this package - am I missing something here?

I haven't looked into the `Sending emails` section deeply, but I did notice that at the very least the `M` in `EMailHeader` is capitalized, whereas it should be `EmailHeader`.

**Comment by AdamChlupacek** [comment]
@dcohen21 Hey, sorry for such a late reply. I will go through the Readme and fix all the examples. We are still in kind of development with the library. I will try to get the Readme into some usable state.

**Comment by vatel** [comment]
me too, I can not resolve the problem with imap.client. Could you please help?

**Comment by vatel** [comment]
I was able to compile the code (see attached file) with some modifications, but it just establishes a TCP connection to gmail: SYN -> SYN+ACK -> ACK and nothing more, event no TLS connection. It does not send any data.
[ImapTest.txt](https://github.com/Spinoco/fs2-mail/files/1928317/ImapTest.txt)

How to run it correctly?

P.S. I am not familiar with fs2 nor streams, so I may be completely wrong... This is just an attempt

**Comment by AdamChlupacek** [comment]
@vatel sorry for late response, you can try to hit me on gitter next time, I am there all the time a and usually have time to reply atleast the basic stuff. 

Could you try to write an empty chunk into the TLS socket? I think you are hitting one really dumb error in fs2-crypto, which I have not yet gotten around to fix :/

**Comment by vatel** [comment]
@AdamChlupacek thank you for response! I will try to do more experiments with TLS. Unfortunately for the moment I am not familiar with fs-* libraries at all (nor streaming concepts), so this is a bit difficult. Any working example of IMAP would be really appreciated!

**Comment by AdamChlupacek** [comment]
@vatel do ask in the fs2 gitter about anything fs2 related, there is great community of people who will reply to basically an fs2 and FP problem you have.

**Comment by AdamChlupacek** [comment]
@dcohen21 @vatel Just quick clarify to the API until I have time to properly give some love to the readMe.

the SSLEngine is not created since it kinda depends on your environment and where you will be connecting to. But in general if you want to jsut test it is ok to create one with default trust store, using: 

```scala
import javax.net.ssl.SSLContext

val ctx = SSLContext.getInstance("TLS")
ctx.init(null, null, null)

val engine = ctx.createSSLEngine()
engine.setUseClientMode(true)

```

As for the `imap.client` that seems to be an oversight in the API, it is meant to exist but seems we forgot to do so. you can use `IMAPClient.mk` instead of it.

If you are using either IMAP or SMTP over TLS please do write an empty chunk first into the socket. As I said before, there are cases with TLS engine where you will not get any data unless you do so. This can be done via: 

```scala
io.tcp.client[Task](new InetSocketAddress("hostName", 993)).flatMap { tcpSocket =>
Stream.eval(TLSEngine[Task](clientTLS)).flatMap { tlsEngine =>
Stream.eval(TLSSocket[Task](tcpSocket, tlsEngine)).flatMap { tlsSocket =>
Stream.eval(tlsSocket.write(Chunk.empty, None)).flatMap { _ =>
  ??? // <- create the desired imap/smtp client
}}}}
```

**Comment by vatel** [comment]
@AdamChlupacek thank you for sharing the code sending empty chunk! It has fixed the problem. So the example seems working now (the complete code is attached).
[ImapTest.txt](https://github.com/Spinoco/fs2-mail/files/1950235/ImapTest.txt)

**Comment by vatel** [comment]
Unfortunately, now I am stuck trying to read mail content. I have added the following block (which tries to read the 1st message in INBOX): 
```
...
imapClient.select(tag[MailboxName]("INBOX")).flatMap { inboxStatus =>
                    println(s"inboxStatus = $inboxStatus")
                    imapClient.bodyStructureOf(tag[imap.MailUID](inboxStatus.getOrElse(null).uidNext)).map { bodyParts =>
                      println(s"bodyParts = $bodyParts")
                    }
...
```

but it gives error:
```
Exception in thread "main" java.lang.Throwable: Could not find start of body structure.
	at spinoco.fs2.mail.imap.IMAPClient$impl$.parseBodyStructure(IMAPClient.scala:381)
	at spinoco.fs2.mail.imap.IMAPClient$$anon$1.$anonfun$bodyStructureOf$1(IMAPClient.scala:205)
...
```

**Comment by AdamChlupacek** [comment]
Just a few things, do not use `null` no fs2-* libraries are ready for that, and they will most likely fail horribly if they encounter it. 

The exception you are seeing is since the email you are trying to get does not exists. the `uidNext` gives the id of the next email that will appear at some time in the future. it is not yet an existing email.

**Comment by vatel** [comment]
@AdamChlupacek, yes of course, 'null' was just a quick stub.
Seems I do not understand how to list all (or unread only) messages in INBOX and then read message content by its ID - could you please point to correct call sequence? I was trying to call imapClient.emailHeaders(0L to Long.MaxValue) but it gives  error (seems no such IDs).

**Comment by vatel** [comment]
@AdamChlupacek, I have found the answer:
imapClient.search(IMAPSearchTerm.ALL) returns all MailUIDs (also I see there IMAPSearchTerm.UNSEEN), after that I call imapClient.bodyStructureOf(_MailUID_)
Sorry for my previous post ;-)

**Comment by vatel** [comment]
@AdamChlupacek, is it possible to get the whole message content (including all headers and body parts) without parsing it and splitting to body parts? I see how to get text or bytes per specified body part, but seems I can not get content 'as is' (as byte array for example). For our purposes we need to take the whole message and pass it to further processing.

**Comment by AdamChlupacek** [comment]
@vatel Glad you found solution to your problem. Currently it is split headers and body parts separately. as for getting the whole body strictly into byte array etc, its just about running the `Stream[F, Byte]` and forcing it in to an array. There was actually discussion about  this exact thing on gitter in fs2 channel (https://gitter.im/functional-streams-for-scala/fs2?at=5ae22737aeadbe0cc5297441).

**Comment by vatel** [comment]
@AdamChlupacek, thanks, I will dive into that discussion and try to understand. Streaming stuff is still too much complicated for me for the moment :-)

**Comment by vatel** [comment]
@AdamChlupacek,

> as for getting the whole body strictly into byte array etc, its just about running the Stream[F, Byte] and forcing it in to an array

Could you please help - how to apply it after calling
`imapClient.search(IMAPSearchTerm.ALL).flatMap { searchResult =>`

So given I have a list of MailUIDs in searchResult, how to fetch the whole message by UID (without splitting to body parts)?

**Comment by AdamChlupacek** [comment]
@vatel Sadly you cannot do it in any other way than it being split in body parts. I am not aware of any other way that IMAP would provide.

**Comment by vatel** [comment]
@AdamChlupacek, according to RFC-3501 it is [possible](https://tools.ietf.org/html/rfc3501#section-6.4.5) to fetch the whole message using BODY[] in FETCH command. I have patched IMAPClient.scala, added the following method:
```
def bytesOf(uid: @@[Long, MailUID]): Stream[F, Byte] = {
   val content = IMAPFetchContent.Body()
   rawContent(request(UID(Fetch(NumericRange(uid: Long, uid: Long, 1), Seq(content))))) through
   fetchBytesOf(0, content.content, "BINARY")
}
```
It works, giving message bytes as Stream (I print bytes to console and compare them to original message source).

The question now is how to write that Stream to Byte[] or something like this. How can I see when EOF is reached? Is there some kind of marker sent when the Stream ends? This question is not specific for the added method though.

**Comment by jarrodu** [comment]
Hello. I have just started to dig into this project. It looks very modern and fun to work with.

I am wondering what it would take to close this issue. It does not seem like this thread stayed on topic and I am not sure what parts are important or not for running the examples in the readme.

Are there any currently working examples that I can use to get better acquainted with the library?

**Comment by AdamChlupacek** [comment]
@jarrodu Hey there, you can use the example I gave on the 25th april here. I will try to get the fixes ASAP into the ReadMe file, sorry, I have been terribly busy, I will get it done over this weekend.

**Comment by jarrodu** [comment]
Hi Adam. Thanks for your quick reply.

And there is not need to work on the weekend. I don't expect that kind of service from an OSS project. :1st_place_medal:

**Comment by vatel** [comment]
>> I will try to get the fixes ASAP into the ReadMe file

Adam, please also add code demonstrating how to "close" IMAPClient - I mean how to release all related resources after reading folder and email content, assuming that IMAP is just a part of work for most people - for example someone wants to read a message to byte array for further processing and when the read is fully-done (how to recognize this?) he wants to close all that stuff and go to some other work.
